version: '3'

services:
  nginx:
    image: yutkin/nginx-certbot:latest
    build:
      context: ./src
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx-certbot.env
    networks:
      services:
        ipv4_address: 192.168.100.2
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)
      # - ./user_conf.d:/etc/nginx/user_conf.d    # or a host mount with a relative or full path.

volumes:
  nginx_secrets:

networks:
  services:
    name: hexos-services
    external: true