version: '3'

services:
  nginx:
    image: yutkin/nginx-certbot:latest
    build:
      context: ./src
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL:?error}
      # Optional (Defaults)
      - DHPARAM_SIZE=${DHPARAM_SIZE:-2048}
      - ELLIPTIC_CURVE=${ELLIPTIC_CURVE:-secp256r1}
      - RENEWAL_INTERVAL=${RENEWAL_INTERVAL:-8d}
      - RSA_KEY_SIZE=${RSA_KEY_SIZE:-2048}
      - STAGING=${STAGING:-0}
      - USE_ECDSA=${USE_ECDSA:-1}
      # Advanced (Defaults)
      - CERTBOT_AUTHENTICATOR=${CERTBOT_AUTHENTICATOR:-webroot}
      - CERTBOT_DNS_PROPAGATION_SECONDS=${CERTBOT_DNS_PROPAGATION_SECONDS}
      - DEBUG=${DEBUG:-0}
      - USE_LOCAL_CA=${USE_LOCAL_CA:-0}

    networks:
      services:
        ipv4_address: ${NGINX_IPV4_ADDR:?error}
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)

volumes:
  nginx_secrets:

networks:
  services:
    name: hexos-services
    external: true
