version: '3'

services:
  nginx:
    image: yutkin/nginx-certbot:latest
    build:
      context: ./src
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      # Optional (Defaults)
      - DHPARAM_SIZE=${DHPARAM_SIZE}
      - ELLIPTIC_CURVE=${ELLIPTIC_CURVE}
      - RENEWAL_INTERVAL=${RENEWAL_INTERVAL}
      - RSA_KEY_SIZE=${RSA_KEY_SIZE}
      - STAGING=${STAGING}
      - USE_ECDSA=${USE_ECDSA}
      # Advanced (Defaults)
      - CERTBOT_AUTHENTICATOR=${CERTBOT_AUTHENTICATOR}
      - CERTBOT_DNS_PROPAGATION_SECONDS=${CERTBOT_DNS_PROPAGATION_SECONDS}
      - DEBUG=${DEBUG}
      - USE_LOCAL_CA=${USE_LOCAL_CA}

    networks:
      services:
        ipv4_address: ${NGINX_IPV4_ADDR}
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)

volumes:
  nginx_secrets:

networks:
  services:
    name: hexos-services
    external: true
